// src/lib/schedule.ts
// Pure helpers that shape RPHQ report rows into the dated schedule used by the
// classes page. Shared by the SSR endpoint (src/pages/api/classes.json.ts) and
// the cron Worker (worker/index.ts), so it must stay free of any runtime-,
// fetch-, or platform-specific code.
import type { ReportRow } from './rphq';

/** KV key under which the cron Worker stores the shaped schedule payload. */
export const SCHEDULE_KV_KEY = 'schedule:current';

export interface DaySchedule {
  /** ISO date key (YYYY-MM-DD) — used for chronological sorting. */
  date: string;
  /** Human label, e.g. "Thu, Jun 5". */
  label: string;
  classes: string[];
}

/** Shape stored in KV and returned (unwrapped) by the endpoint. */
export interface SchedulePayload {
  /** ISO timestamp of when this snapshot was generated by the cron Worker. */
  generatedAt: string;
  /** execute() __typename from the report run. */
  status: string;
  schedule: DaySchedule[];
}

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTHS = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];

/** Find the value of the first row key whose name matches one of `candidates`. */
function pick(row: ReportRow, candidates: string[]): string {
  const keys = Object.keys(row);
  for (const candidate of candidates) {
    const key = keys.find((k) => k.trim().toLowerCase() === candidate.toLowerCase());
    if (key != null && row[key] != null) return String(row[key]);
  }
  // looser contains-match fallback (handles "Session Start Local Datetime Value")
  for (const candidate of candidates) {
    const key = keys.find((k) => k.toLowerCase().includes(candidate.toLowerCase()));
    if (key != null && row[key] != null) return String(row[key]);
  }
  return '';
}

/**
 * Parse an RPHQ "Local Datetime Value" like "2026-06-05 08:00:00".
 * Treated as wall-clock local time (no timezone math) since the report already
 * localizes it. Returns null if it doesn't parse.
 */
function parseLocalDatetime(
  value: string,
): { dateKey: string; label: string; time: string; minutesOfDay: number } | null {
  const m = value.trim().match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})/);
  if (!m) return null;
  const [, y, mo, d, hh, mm] = m;
  const date = new Date(Number(y), Number(mo) - 1, Number(d), Number(hh), Number(mm));
  if (Number.isNaN(date.getTime())) return null;

  const dateKey = `${y}-${mo}-${d}`;
  const label = `${WEEKDAYS[date.getDay()]}, ${MONTHS[Number(mo) - 1]} ${Number(d)}`;
  const hour = Number(hh);
  const minute = Number(mm);
  const period = hour < 12 ? 'AM' : 'PM';
  const hour12 = hour % 12 === 0 ? 12 : hour % 12;
  const time = minute === 0 ? `${hour12} ${period}` : `${hour12}:${String(minute).padStart(2, '0')} ${period}`;
  return { dateKey, label, time, minutesOfDay: hour * 60 + minute };
}

/**
 * Group dated session rows by calendar date. Each row is one session
 * occurrence: course title + start/end datetime + instructor. We keep the real
 * date (not a generic weekday), order days chronologically, and order each
 * day's classes by start time.
 */
export function toSchedule(rows: ReportRow[]): DaySchedule[] {
  // Each row is one session, but the report can emit duplicates (same course at
  // the same start time on the same day). We collapse those to a single entry
  // per date, keyed by the "Course (time)" label. We read ONLY the course title
  // and start time; the instructor's customer id (the report's only PII) is
  // never copied into the output.
  const byDate = new Map<string, { label: string; items: Map<string, number> }>();

  for (const row of rows) {
    const name = pick(row, [
      'course public title text',
      'course',
      'class',
      'program',
      'title',
      'name',
    ]);
    const start = pick(row, ['session start', 'start', 'start time', 'starttime']);
    if (!name || !start) continue;

    const parsed = parseLocalDatetime(start);
    if (!parsed) continue;

    const entry = byDate.get(parsed.dateKey) ?? { label: parsed.label, items: new Map() };
    const text = `${name} (${parsed.time})`;
    if (!entry.items.has(text)) entry.items.set(text, parsed.minutesOfDay); // dedupe: first wins
    byDate.set(parsed.dateKey, entry);
  }

  return [...byDate.entries()]
    .sort(([a], [b]) => a.localeCompare(b)) // ISO date keys sort chronologically
    .map(([date, { label, items }]) => ({
      date,
      label,
      classes: [...items.entries()].sort((a, b) => a[1] - b[1]).map(([text]) => text),
    }));
}
