name = "theknot-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "a134e104017c4111af5973a85d7d43de"
preview_id = "9ced4b54c59f43b4aee1c310dae6a798"

# Schedule snapshot, written by the cron Worker (worker/) and read by the
# /api/classes.json endpoint. Same namespace must be bound in worker/wrangler.toml.
# Create it with: wrangler kv namespace create SCHEDULE_KV
[[kv_namespaces]]
binding = "SCHEDULE_KV"
id = "77b4a83eeaad458e82b4fc09e4bd6248"
preview_id = "8b1dff75dd974f67b38978399c8ff5cd"
